routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', 'IndexController');
Route::resource('adverts', 'AdvertController')->only(['index', 'show']);
Route::resource('categories', 'CategoryController')->only(['index', 'show']);
Route::resource('images', 'ImageController')->only(['store', 'destroy']);

Auth::routes();

Route::namespace('Admin')
    ->prefix('admin')
    ->name('admin.')
    ->middleware('auth')
    ->group(function () {
        Route::get('/', 'IndexController')->name('index');
        Route::patch('adverts/{advert}/restore', 'AdvertController@restore')
            ->name('adverts.restore');
        Route::resource('adverts', 'AdvertController')
            ->except(['show']);
        Route::patch('categories/{category}/restore', 'CategoryController@restore')
            ->name('categories.restore');
        Route::resource('categories', 'CategoryController')
            ->except(['show']);
        Route::patch('users/{user}/restore', 'UserController@restore')
            ->name('users.restore');
        Route::resource('users', 'UserController')
            ->except(['show']);
        Route::resource('profile', 'ProfileController')
            ->only(['show', 'edit', 'update'])
            ->parameters(['profile' => 'user']);
    });

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes;

    const ID_ROLE_ADMINISTRATOR = 1;
    const ID_ROLE_CLIENT = 2;

    const NAME_ROLE_ADMINISTRATOR = 'Administrator';
    const NAME_ROLE_CLIENT = 'Client';

    const ROLES = [
        self::ID_ROLE_ADMINISTRATOR => self::NAME_ROLE_ADMINISTRATOR,
        self::ID_ROLE_CLIENT => self::NAME_ROLE_CLIENT
    ];


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Get the user's role name.
     *
     * @param  User $user
     * @return string
     */
    public function getRoleNameAttribute()
    {
        return self::ROLES[$this->role_id];
    }

    /**
     * Get the user's image.
     */
    public function image()
    {
        return $this->morphOne(Image::class, 'imageable');
    }

    /**
     * The adverts that belong to the user.
     */
    public function adverts()
    {
        return $this->hasMany(Advert::class);
    }

    /**
     * Scope a query to only include users with administrator role
     *
     * @param Builder $query
     * @param string $slug
     * @return Builder
     */
    public function scopeAdministrator($query)
    {
        return $query->where('role_id', User::ID_ROLE_ADMINISTRATOR);
    }

    /**
     * Scope a query to only include users with client role
     *
     * @param Builder $query
     * @param string $slug
     * @return Builder
     */
    public function scopeClient($query)
    {
        return $query->where('role_id', User::ID_ROLE_CLIENT);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\User;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $usersQuery = User::query();

        $usersQuery->when(request('only_trashed'), function ($query) {
            return $query->onlyTrashed();
        });

        $usersQuery->when(request('administrator'), function ($query) {
            return $query->administrator();
        });


        $users = $usersQuery->latest('updated_at')->paginate();

        return view('admin.users.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.users.create', ['roles' => User::ROLES]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreUserRequest $request
     * @return Response
     */
    public function store(StoreUserRequest $request)
    {
        $data = $request->validated();

        $data['password'] = Hash::make($data['password']);

        User::create($data);

        return redirect()->route('admin.users.index')
            ->with('status', 'User successfully added!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @return Response
     */
    public function edit(User $user)
    {
        return view('admin.users.edit', [
            'user' => $user,
            'roles' => User::ROLES
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateUserRequest $request
     * @param User $user
     * @return Response
     */
    public function update(UpdateUserRequest $request, User $user)
    {
        $data = $request->validated();

        if (empty($data['password'])) {
            unset($data['password']);
        } else {
            $data['password'] = Hash::make($data['password']);
        }

        $user->update($data);

        return redirect()->route('admin.users.index')
            ->with('status', 'User successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param User $user
     * @return Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('admin.users.index')
            ->with('status', 'User successfully deleted!');
    }

    /**
     * Restore the specified resource
     *
     * @param int $id
     * @return Response
     */
    public function restore($id)
    {
        User::onlyTrashed()->where('id', $id)->restore();

        return redirect()->route('admin.users.index', ['only_trashed' => 1])
            ->with('status', 'User successfully restored!');
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.admin.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-6 offset-lg-3">
                <h2 class="mt-3">Create user</h2>
            </div>
            <form class="col-lg-6 offset-lg-3" method="post" action="{{ route('admin.users.store') }}">
                @csrf
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name') }}">
                    @error('name')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="text" class="form-control @error('email') is-invalid @enderror" id="email" name="email" value="{{ old('email') }}">
                    @error('email')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="password">{{ __('Password') }}</label>
                    <input type="password" class="form-control @error('password') is-invalid @enderror" id="password" name="password">
                    @error('password')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="password-confirm">{{ __('Confirm Password') }}</label>
                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation">
                </div>
                <div class="form-group">
                    <label for="role_id">Role</label>
                    <select class="form-control @error('role_id') is-invalid @enderror" id="role_id" name="role_id">
                        @foreach($roles as $key => $role)
                        <option value="{{ $key }}">{{ $role }}</option>
                        @endforeach
                    </select>
                    @error('role_id')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
                <a href="{{ route('admin.users.index') }}" class="btn btn-light pull-right">Chancel</a>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.admin.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-6 offset-lg-3">
                <h2 class="mt-3">Edit user</h2>
            </div>
            <form class="col-lg-6 offset-lg-3" method="post" action="{{ route('admin.users.update', $user) }}">
                @method('PUT')
                @csrf
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $user->name) }}">
                    @error('name')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="text" class="form-control @error('email') is-invalid @enderror" id="email" name="email" value="{{ old('email', $user->email) }}">
                    @error('email')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="password">{{ __('Password') }}</label>
                    <input type="password" class="form-control @error('password') is-invalid @enderror" id="password" name="password">
                    @error('password')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="password-confirm">{{ __('Confirm Password') }}</label>
                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation">
                </div>
                <div class="form-group">
                    <label for="role_id">Role</label>
                    <select class="form-control @error('role_id') is-invalid @enderror" id="role_id" name="role_id">
                        @foreach($roles as $key => $role)
                            <option value="{{ $key }}" @if($user->role_id == $key) selected @endif>{{ $role }}</option>
                        @endforeach
                    </select>
                    @error('role_id')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
                <a href="{{ route('admin.users.index') }}" class="btn btn-light pull-right">Chancel</a>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin.app')

@section('content')

    <div class="container">
        <div class="row">
            <nav class="navbar navbar-light">
                <a href="{{ route('admin.users.create') }}" class="btn btn-success">Create user</a>
            </nav>
            @include('admin.filters')
            <div class="container">
                <a class="btn btn-light @if (request()->has('administrator')) active @endif"
                   href="{{ route(Route::currentRouteName(), ['administrator' => 1]) }}">
                    Administrator
                </a>
            </div>
            <table class="table mt-4">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Role</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($users as $user)
                    <tr>
                        <th scope="row">{{ $user->id }}</th>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->role_name }}</td>
                        <td>
                            @if($user->trashed())
                                <input type="submit" class="btn btn-dark" form="restore-item"
                                       formaction="{{ route('admin.users.restore', $user) }}" value="Restore">
                            @else
                                <a href="{{ route('admin.users.edit', $user) }}" class="btn btn-warning">
                                    Edit
                                </a>
                                <input type="submit" class="btn btn-danger" form="delete-item"
                                       formaction="{{ route('admin.users.destroy', $user) }}" value="Delete">
                            @endif
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <form id="restore-item" method="POST">
                @method('PATCH')
                @csrf
            </form>
            <form id="delete-item" method="POST">
                @method('DELETE')
                @csrf
            </form>
            {{ $users->links() }}
        </div>
    </div>

@endsection