routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', 'IndexController');
Route::resource('adverts', 'AdvertController')->only(['index', 'show']);
Route::resource('categories', 'CategoryController')->only(['index', 'show']);
Route::resource('images', 'ImageController')->only(['store', 'destroy']);

Auth::routes();

Route::namespace('Admin')
    ->prefix('admin')
    ->name('admin.')
    ->middleware('auth')
    ->group(function () {
        Route::get('/', 'IndexController')->name('index');
        Route::patch('adverts/{advert}/restore', 'AdvertController@restore')
            ->name('adverts.restore');
        Route::resource('adverts', 'AdvertController')
            ->except(['show']);
        Route::patch('categories/{category}/restore', 'CategoryController@restore')
            ->name('categories.restore');
        Route::resource('categories', 'CategoryController')
            ->except(['show']);
        Route::patch('users/{user}/restore', 'UserController@restore')
            ->name('users.restore');
        Route::resource('users', 'UserController')
            ->except(['show']);
        Route::resource('profile', 'ProfileController')
            ->only(['show', 'edit', 'update'])
            ->parameters(['profile' => 'user']);
    });

app/Advert.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Advert extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'slug', 'description', 'user_id'
    ];

    /**
     * The categories that belong to the advert.
     */
    public function categories()
    {
        return $this->belongsToMany(Category::class)->withTimestamps();
    }

    /**
     * Get all of the advert's images.
     */
    public function images()
    {
        return $this->morphMany(Image::class, 'imageable');
    }

    /**
     * Get user who created article.
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    /**
     * Scope a query to only include advert by a given slug.
     *
     * @param Builder $query
     * @param string $slug
     * @return Builder
     */
    public function scopeBySlug($query, $slug)
    {
        return $query->where('slug', $slug);
    }
}

app/Image.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Image
 * @package App
 */
class Image extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'files',
        'imageable_id',
        'imageable_type'
    ];

    /**
     * Get the owning imageable model.
     */
    public function imageable()
    {
        return $this->morphTo();
    }

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'name';
    }

    /**
     * @return string
     */
    public function getImagePathAttribute()
    {
        return "{$this->created_at->format('Y/m')}/{$this->name}";
    }

    /**
     * @return string
     */
    public function getThumbPathAttribute()
    {
        list('filename' => $filename, 'extension' => $extension) = pathinfo($this->name);
        return "{$this->created_at->format('Y/m')}/{$filename}_thumbnail.{$extension}";
    }

}

app/Http/Controllers/Admin/AdvertController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Advert;
use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreAdvertRequest;
use App\Http\Requests\UpdateAdvertRequest;
use App\Image;
use Illuminate\Http\Response;
use Illuminate\Support\Str;

/**
 * Class AdvertController
 * @package App\Http\Controllers\Admin
 */
class AdvertController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $advertsQuery = Advert::query();

        $advertsQuery->when(request('only_trashed'), function ($query) {
            return $query->onlyTrashed();
        });

        $adverts = $advertsQuery->latest('updated_at')->paginate();

        return view('admin.adverts.index', ['adverts' => $adverts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $categories = Category::all();

        return view('admin.adverts.create', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreAdvertRequest $request
     * @return Response
     */
    public function store(StoreAdvertRequest $request)
    {
        $data = $request->validated();

        if (empty($data['slug'])) {
            $data['slug'] = Str::slug($data['title']);
        }

        $data['user_id'] = auth()->user()->id;

        $advert = Advert::create($data);
        $advert->categories()->sync($data['categories']);

        if (isset($data['image_ids'])) {
            foreach ($data['image_ids'] as $imageId) {
                $image = Image::find($imageId);
                $image->update([
                    'imageable_id' => $advert->id,
                    'imageable_type' => Advert::class,
                ]);
            }
        }

        return redirect()->route('admin.adverts.index')
            ->with('status', 'Advert successfully added!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Advert $advert
     * @return Response
     */
    public function edit(Advert $advert)
    {
        $categories = Category::all();

        return view('admin.adverts.edit', ['advert' => $advert, 'categories' => $categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateAdvertRequest $request
     * @param Advert $advert
     * @return Response
     */
    public function update(UpdateAdvertRequest $request, Advert $advert)
    {
        $data = $request->validated();

        if (empty($data['slug'])) {
            $data['slug'] = Str::slug($data['title']);
        }

        $advert->update($data);

        $advert->categories()->sync($data['categories']);

        return redirect()->route('admin.adverts.index')
            ->with('status', 'Advert successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Advert $advert
     * @return Response
     */
    public function destroy(Advert $advert)
    {
        $advert->delete();

        return redirect()->route('admin.adverts.index')
            ->with('status', 'Advert successfully deleted!');
    }

    /**
     * Restore the specified resource
     *
     * @param string $slug
     * @return Response
     */
    public function restore($slug)
    {
        Advert::onlyTrashed()->bySlug($slug)->restore();

        return redirect()->route('admin.adverts.index', ['only_trashed' => 1])
            ->with('status', 'Advert successfully restored!');
    }
}

app/Http/Controllers/AdvertController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Advert;
use Illuminate\Http\Response;

class AdvertController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $adverts = Advert::with('images')
            ->latest('updated_at')
            ->paginate();

        return view('adverts.index', ['adverts' => $adverts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param App\Advert $advert
     * @return Response
     */
    public function show(Advert $advert)
    {
        $similarAdverts = Advert::with('images')
            ->whereHas('categories', function ($query) use ($advert) {
                $query->whereIn('category_id', $advert->categories->pluck('id'));
            })
            ->where('id', '!=', $advert->id)
            ->inRandomOrder()
            ->limit(3)
            ->get();

        $advert->increment('views');

        return view('adverts.show', [
            'advert' => $advert,
            'similarAdverts' => $similarAdverts
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Api/AdvertController.php
<?php

namespace App\Http\Controllers\API;

use App\Advert;
use App\Http\Controllers\Controller;
use App\Http\Resources\AdvertResource;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class AdvertController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return JsonResponse
     */
    public function index()
    {
        $perPage = request()->query('per_page') ?? null;

        $advertsQuery = Advert::query();

        $advertsQuery->when(request('category_id'), function ($query, $categoryId) {
            return $query->whereHas('categories', function ($query) use ($categoryId) {
                $query->where('category_id', $categoryId);
            });
        })->when(request('similar_by_id'), function ($query, $similarById) {
            return $query->whereHas('categories', function ($query) use ($similarById) {
                $query->whereIn('category_id', Advert::find($similarById)->categories->pluck('id'));
            })->where('id', '!=', $similarById)
                ->inRandomOrder();
        });

        $adverts = $advertsQuery->with('images')->latest('updated_at')->paginate($perPage);

        return AdvertResource::collection($adverts);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/adverts/create.blade.php
@extends('layouts.admin.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-6 offset-lg-3">
                <h2 class="mt-3">Create advert</h2>
            </div>
            <form class="advert-create col-lg-6 offset-lg-3" method="post" action="{{ route('admin.adverts.store') }}">
                @csrf
                <div class="form-group">
                    <label for="title">Title:</label>
                    <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title" value="{{ old('title') }}">
                    @error('title')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="slug">Slug:</label>
                    <input type="text" class="form-control @error('slug') is-invalid @enderror" id="slug" name="slug" value="{{ old('slug') }}">
                    @error('slug')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="categories">Category:</label>
                    <select class="form-control @error('categories') is-invalid @enderror" multiple id="categories" name="categories[]">
                        @foreach($categories as $category)
                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                    @error('categories')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>
                <div class="form-group">
                    <label class="form-check-label" for="description">Description:</label>
                    <textarea class="form-control @error('description') is-invalid @enderror" id="description" name="description" rows="5">{{ old('description') }}</textarea>
                    @error('description')
                    <span class="invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
                <a href="{{ route('admin.adverts.index') }}" class="btn btn-light pull-right">Chancel</a>
            </form>
        </div>
        <div class="container">
            <form method="post" action="{{ route('images.store') }}" enctype="multipart/form-data">
                @csrf
                <input type="hidden" name="imageable_id" value="">
                <input type="hidden" name="imageable_type" value="">
                <div class="col-6 float-right">
                    <div class="custom-file">
                        <input class="custom-file-input" id="fileupload" type="file" name="files[]"
                               data-url="{{ route('images.store') }}" multiple>
                        <label class="custom-file-label" for="validatedCustomFile">Add image...</label>
                    </div>
                </div>
            </form>
            <br>
            <h1 class="font-weight-light text-center text-lg-left mt-4 mb-0">Images</h1>

            <hr class="mt-2 mb-5">

            <div class="files row text-center text-lg-left">

            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $(() => {

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
            });

            $('#fileupload').fileupload({
                dataType: 'json',
                add: (e, data) => {
                    $('input.custom-file-input').removeClass('is-invalid');

                    let uploadErrors = [];
                    let acceptFileTypes = /^image\/(gif|jpe?g|png)$/i;

                    $.each(data.originalFiles, (index, file) => {
                        if (file['type'].length && !acceptFileTypes.test(file['type'])) {
                            uploadErrors.push('Not an accepted file type');
                            return false;
                        }

                        if (file['size'].length && file['size'] > 5000000) {
                            uploadErrors.push('Filesize is too big');
                            return false;
                        }
                    });

                    if (uploadErrors.length > 0) {
                        $('input.custom-file-input').addClass('is-invalid');
                        $('label.custom-file-label').after(`<span class="invalid-feedback">${uploadErrors.join("\n")}</span>`);
                        return false;
                    } else {
                        data.submit();
                    }
                },
                done: (e, data) => {
                    let url = data.jqXHR.responseJSON.url;
                    let name = data.jqXHR.responseJSON.name;
                    let id = data.jqXHR.responseJSON.id;

                    $('div.files').append(`<div class="col-lg-3 col-md-4 col-6">` +
                        `<div class="d-block mb-4 h-100">` +
                        `<img class="img-fluid img-thumbnail" src="${url}" alt="">` +
                        `<a class="delete-link" data-id="${id}" href="/images/${name}">delete</a>` +
                        `</div></div>`);

                    $('form.advert-create').append(`<input type="hidden" name="image_ids[]" value="${id}">`);

                    $('div.files').before('<div class="alert alert-success" role="alert">Images successfully added.</div>');
                    setTimeout(() => {
                        $('div.alert-success').fadeOut();
                    }, 2000);
                },
                fail: (e, data) => {
                    let errors = data.jqXHR.responseJSON;
                    $('input.custom-file-input').addClass('is-invalid');
                    $('label.custom-file-label').after(`<span class="invalid-feedback">${errors.message}</span>`);
                }
            });

            $('div.files').on('click', 'a.delete-link', (e) => {
                e.preventDefault();

                $el = $(e.currentTarget);

                $.ajax({
                    url: $el.attr('href'),
                    type: 'POST',
                    data: {_method: 'DELETE'},
                    success: (result) => {
                        $(`input[value="${$el.data('id')}"]`).remove();
                        $el.parent().fadeOut(200, () => {
                            $el.parent().parent().remove();
                        });
                    }
                });
            })
        });
    </script>
@endsection

resources/views/admin/adverts/edit.blade.php
@extends('layouts.admin.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="container">
                <div class="col-lg-6 offset-lg-3">
                    <h2 class="mt-3">Edit advert</h2>
                </div>
                <form class="col-lg-6 offset-lg-3" method="post" action="{{ route('admin.adverts.update', $advert) }}">
                    @method('PUT')
                    @csrf
                    <div class="form-group">
                        <label for="title">Title:</label>
                        <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title" value="{{ old('title', $advert->title) }}">
                        @error('title')
                        <span class="invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="slug">Slug:</label>
                        <input type="text" class="form-control @error('slug') is-invalid @enderror" id="slug" name="slug" value="{{ old('slug', $advert->slug) }}">
                        @error('slug')
                        <span class="invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="categories">Category:</label>
                        <select class="form-control @error('categories') is-invalid @enderror" multiple id="categories" name="categories[]">
                            @foreach($categories as $category)
                                <option value="{{ $category->id }}" @if($advert->categories->contains($category)) selected @endif>{{ $category->name }}</option>
                            @endforeach
                        </select>
                        @error('categories')
                        <span class="invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="form-check-label" for="description">Description:</label>
                        <textarea class="form-control @error('description') is-invalid @enderror" id="description" name="description" rows="5">{{ old('description', $advert->description) }}</textarea>
                        @error('description')
                        <span class="invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="{{ route('admin.adverts.index') }}" class="btn btn-light pull-right">Chancel</a>
                </form>
                <br>
                <form method="post" action="{{ route('images.store') }}" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" name="imageable_id" value="{{ $advert->id  }}">
                    <input type="hidden" name="imageable_type" value="{{ $advert->getMorphClass() }}">
                    <div class="col-6 float-right">
                        <div class="custom-file">
                            <input class="custom-file-input" id="fileupload" type="file" name="files[]"
                                   data-url="{{ route('images.store') }}" multiple>
                            <label class="custom-file-label" for="validatedCustomFile">Add image...</label>
                        </div>
                    </div>
                </form>
                <br>
                <h1 class="font-weight-light text-center text-lg-left mt-4 mb-0">Images</h1>

                <hr class="mt-2 mb-5">

                <div class="files row text-center text-lg-left">
                    @foreach($advert->images as $image)
                        @if(file_exists("storage/images/{$image->thumb_path}"))
                            <div class="col-lg-3 col-md-4 col-6">
                                <image-list-item-component
                                    src="{{ asset("storage/images/{$image->thumb_path}") }}"
                                    alt="{{ $image->name }}"
                                    delete-url="{{ route('images.destroy', $image->name) }}"
                                ></image-list-item-component>
                            </div>
                        @endif
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $(() => {

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
            });

            $('#fileupload').fileupload({
                dataType: 'json',
                add: (e, data) => {
                    $('input.custom-file-input').removeClass('is-invalid');

                    let uploadErrors = [];
                    let acceptFileTypes = /^image\/(gif|jpe?g|png)$/i;

                    $.each(data.originalFiles, (index, file) => {
                        if (file['type'].length && !acceptFileTypes.test(file['type'])) {
                            uploadErrors.push('Not an accepted file type');
                            return false;
                        }

                        if (file['size'].length && file['size'] > 5000000) {
                            uploadErrors.push('Filesize is too big');
                            return false;
                        }
                    });

                    if (uploadErrors.length > 0) {
                        $('input.custom-file-input').addClass('is-invalid');
                        $('label.custom-file-label').after(`<span class="invalid-feedback">${uploadErrors.join("\n")}</span>`);
                        return false;
                    } else {
                        data.submit();
                    }
                },
                done: (e, data) => {
                    let url = data.jqXHR.responseJSON.url;
                    let name = data.jqXHR.responseJSON.name;
                    let id = data.jqXHR.responseJSON.id;

                    $('div.files').append(`<div class="col-lg-3 col-md-4 col-6">` +
                        `<div class="d-block mb-4 h-100">` +
                        `<img class="img-fluid img-thumbnail" src="${url}" alt="">` +
                        `<a class="delete-link" href="/images/${name}">delete</a>` +
                        `</div></div>`);

                    $('div.files').append(`<div id="img-component" src="${url} alt="${url}"></div>`);

                    $('div.files').before('<div class="alert alert-success" role="alert">Images successfully added.</div>');
                    setTimeout(() => {
                        $('div.alert-success').fadeOut();
                    }, 2000);
                },
                fail: (e, data) => {
                    let errors = data.jqXHR.responseJSON;
                    $('input.custom-file-input').addClass('is-invalid');
                    $('label.custom-file-label').after(`<span class="invalid-feedback">${errors.message}</span>`);
                }
            });
        });

    </script>
@endsection

resources/views/admin/adverts/index.blade.php
@extends('layouts.admin.app')

@section('content')

        <div class="container">
            <div class="row">
                <nav class="navbar navbar-light">
                    <a href="{{ route('admin.adverts.create') }}" class="btn btn-success">Create advert</a>
                </nav>
                @include('admin.filters')
                <table class="table mt-4">
                    <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($adverts as $advert)
                    <tr>
                        <th scope="row">{{ $advert->id }}</th>
                        <td>{{ $advert->title }}</td>
                        <td>{{ $advert->description }}</td>
                        <td>
                            @if($advert->trashed())
                                <input type="submit" class="btn btn-dark" form="restore-item"
                                       formaction="{{ route('admin.adverts.restore', $advert) }}" value="Restore">
                            @else
                                <a href="{{ route('admin.adverts.edit', $advert) }}" class="btn btn-warning">
                                    Edit
                                </a>
                                <input type="submit" class="btn btn-danger" form="delete-item"
                                       formaction="{{ route('admin.adverts.destroy', $advert) }}" value="Delete">
                            @endif
                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
                <form id="restore-item" method="POST">
                    @method('PATCH')
                    @csrf
                </form>
                <form id="delete-item" method="POST">
                    @method('DELETE')
                    @csrf
                </form>
                {{ $adverts->links() }}
            </div>
        </div>

@endsection